//@flow
'use strict'
import { digit, word } from './fork'

export const underscore   = word('_')
export const colon        = word(':')
export const semicolon    = word(';')
export const openPar      = word('(')
export const closePar     = word(')')
export const openBracket  = word('[')
export const closeBracket = word(']')
export const openBrace    = word('{')
export const closeBrace   = word('}')
export const tripleMinus  = word('---')
export const natConst     = digit.atLeast(1)
export const equals       = word('=')
export const hash         = word('#')
export const question     = word('?')
export const percent      = word('%')
export const plus         = word('+')
export const langle       = word('<')
export const rangle       = word('>')
export const comma        = word(',')
export const dot          = word('.')
export const asterisk     = word('*')
export const exclMark     = word('!')
export const Final        = word('Final')
export const New          = word('New')
export const Empty        = word('Empty')
